"""updated migration file

Revision ID: 49049e89b022
Revises: ae0c49646eab
Create Date: 2023-07-11 16:54:55.390351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49049e89b022'
down_revision = 'ae0c49646eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'image', ['image_id'], ['id'])
        batch_op.drop_column('friend_id')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['friend_id'], ['id'])
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
